
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DHARUN
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceno = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        one = new javax.swing.JTextField();
        two = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        three = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        serviceno.setBackground(new java.awt.Color(255, 255, 255));
        serviceno.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        serviceno.setForeground(new java.awt.Color(153, 255, 0));
        serviceno.setText("SERVICE NUMBER   :");
        getContentPane().add(serviceno);
        serviceno.setBounds(50, 126, 213, 40);

        pwd.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        pwd.setForeground(new java.awt.Color(153, 255, 0));
        pwd.setText("PASSWORD  :");
        getContentPane().add(pwd);
        pwd.setBounds(130, 210, 150, 40);

        one.setBackground(new java.awt.Color(153, 153, 153));
        one.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        one.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(one);
        one.setBounds(350, 122, 250, 50);

        two.setBackground(new java.awt.Color(153, 153, 153));
        two.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        two.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(two);
        two.setBounds(350, 210, 250, 50);

        login.setBackground(new java.awt.Color(102, 102, 102));
        login.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(0, 255, 255));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(450, 420, 150, 50);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("CASHIER LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 40, 220, 43);

        three.setBackground(new java.awt.Color(153, 153, 153));
        three.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        three.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(three);
        three.setBounds(350, 300, 250, 50);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("RETYPE PASSWORD  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 300, 230, 40);

        register.setBackground(new java.awt.Color(102, 102, 102));
        register.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(51, 255, 255));
        register.setText("help to register  for manager");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(20, 420, 310, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
      String serviceno=one.getText();
      String password=String.valueOf(two.getPassword());
      String retypepassword=String.valueOf(three.getPassword());
      
      String query="SELECT * FROM `cashier` WHERE `serviceno`=? AND`password`=? AND`retypepassword`=?";
      
      PreparedStatement demo;
      ResultSet tom;
      
      try{
          demo=connectivity.getConnection().prepareStatement(query);
          demo.setString(1, serviceno);
          demo.setString(2, password);
          demo.setString(3, retypepassword);
          tom=demo.executeQuery();
          if(tom.next())
          {
              receipt task=new receipt();
              task.setVisible(true);
              this.setVisible(false);
          }
          else
          {
    JOptionPane.showMessageDialog(null,"service number (or) password does not match  please try again");
          }
          
      }catch(Exception judo){
           System.out.println(judo);
      }
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        managerlogin dot = new managerlogin();
        dot.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JTextField one;
    private javax.swing.JLabel pwd;
    private javax.swing.JButton register;
    private javax.swing.JLabel serviceno;
    private javax.swing.JPasswordField three;
    private javax.swing.JPasswordField two;
    // End of variables declaration//GEN-END:variables
}
