import java.sql.*;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.Connection;
//import org.apache.commons.dbutils.DbUtils;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DHARUN
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        one = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        two = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        four = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seven = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        five = new javax.swing.JPasswordField();
        six = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        three = new com.toedter.calendar.JDateChooser();
        search1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table123 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRATION FORM  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 310, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("SERVICE NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 140, 20);

        one.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one);
        one.setBounds(230, 90, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText(" NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 140, 60, 26);

        two.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two);
        two.setBounds(230, 140, 200, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("MOBILE NUMBER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 230, 130, 26);

        four.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four);
        four.setBounds(230, 230, 200, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 280, 100, 26);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("RETYPE PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 330, 160, 26);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 380, 80, 26);

        seven.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        getContentPane().add(seven);
        seven.setBounds(230, 380, 200, 30);

        submit.setBackground(new java.awt.Color(255, 255, 153));
        submit.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(40, 440, 390, 30);

        jButton2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jButton2.setText("back to login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 430, 160, 30);

        five.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        getContentPane().add(five);
        five.setBounds(230, 280, 200, 30);

        six.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        getContentPane().add(six);
        six.setBounds(230, 330, 200, 30);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("DATE OF BIRTH");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 180, 130, 26);
        getContentPane().add(three);
        three.setBounds(230, 180, 200, 30);

        search1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        search1.setText("search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        getContentPane().add(search1);
        search1.setBounds(660, 50, 90, 30);

        update1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        update1.setText("update  >>>");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        getContentPane().add(update1);
        update1.setBounds(520, 270, 160, 30);

        delete1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        delete1.setText("delete  >>>");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete1);
        delete1.setBounds(520, 350, 160, 30);

        Table123.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table123);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 150, 220, 80);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("service no");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 50, 70, 26);

        jet.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jetActionPerformed(evt);
            }
        });
        getContentPane().add(jet);
        jet.setBounds(450, 50, 200, 30);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 770, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked

       
    }//GEN-LAST:event_submitMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String serviceno=one.getText();
        String name=two.getText();
        
        SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-mm-dd");
        String dateofbirth=dateformat.format(three.getDate());
       
        String mobileno=four.getText();

        String password = String.valueOf(five.getPassword());
        String retypepassword=String.valueOf(six.getPassword());
        
        String address=seven.getText();
        
        
        PreparedStatement dairy;
String query="INSERT INTO `cashier`(`serviceno`,`name`,`dateofbirth`,`mobileno`,`password`,`retypepassword`,`address`)values(?,?,?,?,?,?,?)";
 // Int query=""       
        try
        {
            dairy=connectivity.getConnection().prepareStatement(query);
           
            dairy.setString(1,serviceno);
            dairy.setString(2,name);
            dairy.setString(3, dateofbirth);
            dairy.setString(4, mobileno);
            dairy.setString(5, password);
            dairy.setString(6, retypepassword);
            dairy.setString(7, address);
            
            if(dairy.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"registered successfully");
            }
        }catch(Exception exam)
        {
            System.out.println(exam);
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        login text=new login();
        text.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        String service=jet.getText();
        PreparedStatement dora ;
        ResultSet dell;
        
        try{
    String query="SELECT * FROM `cashier` WHERE `serviceno`=?";
    
     dora=connectivity.getConnection().prepareStatement(query);
      dora.setString(1,service);  
     
     dell=dora.executeQuery();
     
     if(dell.next())
     {
        one.setText(dell.getString(2));
        two.setText(dell.getString(3));
        three.setDateFormatString(dell.getString(4));
        four.setText(dell.getString(5));
        five.setToolTipText(dell.getString(6));
        six.setToolTipText(dell.getString(7));
        seven.setText(dell.getString(8));
      
     }
     else
     {
         JOptionPane.showMessageDialog(null, "service number does not exist  !");
     }
        }catch(Exception tom){
            System.out.println(tom);
        }
        
                
      
    }//GEN-LAST:event_search1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String name=two.getText();
        String dateofbirth=three.getDateFormatString();
        String mobileno=four.getText();
        String password=five.getToolTipText();
        String retypepassword=six.getToolTipText();
        String address=seven.getText();
        String serviceno=jet.getText();
        
        PreparedStatement dora;
  String query="UPDATE `cashier` SET `name`=?, `dateofbirth`=?, `mobileno`=?, `password`=?,`retypepassword`=?,`address`=? WHERE `serviceno`=?";
        
        try{
            dora=connectivity.getConnection().prepareStatement(query);
            dora.setString(1, name);
            dora.setString(2,dateofbirth);
            dora.setString(3,mobileno);
            dora.setString(4,password);
            dora.setString(5,retypepassword);
            dora.setString(6,address);
            dora.setString(7, serviceno);
            
            if(dora.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "updated successfully !");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"service number does not match buddy !");
            }
                  
        }catch(SQLException doc){
            System.out.println(doc);
        }
    }//GEN-LAST:event_update1ActionPerformed

    private void jetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jetActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
       String  service=jet.getText();
int a=JOptionPane.showConfirmDialog(null, "do you want delete","select", JOptionPane.YES_NO_CANCEL_OPTION );   
     
     PreparedStatement dora;
     if(a==0)
     {
         String query="DELETE FROM  `cashier` WHERE `serviceno`=?";
     try{
         dora=connectivity.getConnection().prepareStatement(query);
         
         dora.setString(1, service);
     if(dora.executeUpdate()>0)
     {
         JOptionPane.showMessageDialog(null, "deleted successfully !");
     }
     else{
         JOptionPane.showMessageDialog(null, "your mobile number does not exit !");
     }
     }catch(Exception jam){
          System.out.println(jam);
     }
     }
    }//GEN-LAST:event_delete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table123;
    private javax.swing.JButton delete1;
    private javax.swing.JPasswordField five;
    private javax.swing.JTextField four;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jet;
    private javax.swing.JTextField one;
    private javax.swing.JButton search1;
    private javax.swing.JTextField seven;
    private javax.swing.JPasswordField six;
    private javax.swing.JButton submit;
    private com.toedter.calendar.JDateChooser three;
    private javax.swing.JTextField two;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
